permalink: /:year/:month/:title
relative_permalinks: false
markdown: kramdown
exclude: ['Rakefile', 'CNAME', 'README.md', 'config.rb']

url: http://tlof.aniketpant.com

title: "Thousand Lamps On Fire"
