permalink: /:year/:month/:title
relative_permalinks: false
markdown: kramdown
exclude: ['Rakefile', 'CNAME', 'README.md', 'config.rb']

url: http://rawrrr.github.com/tlof

title: "Thousand Lamps On Fire"
